[2023-03-25T20:19:31.990+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data_v0.download_weather_data manual__2023-03-25T20:19:30.938712+00:00 [queued]>
[2023-03-25T20:19:32.009+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data_v0.download_weather_data manual__2023-03-25T20:19:30.938712+00:00 [queued]>
[2023-03-25T20:19:32.009+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T20:19:32.009+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T20:19:32.009+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T20:19:32.034+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 20:19:30.938712+00:00
[2023-03-25T20:19:32.042+0000] {standard_task_runner.py:55} INFO - Started process 258 to run task
[2023-03-25T20:19:32.046+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data_v0', 'download_weather_data', 'manual__2023-03-25T20:19:30.938712+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmplyxvt2np']
[2023-03-25T20:19:32.048+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask download_weather_data
[2023-03-25T20:19:32.140+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data_v0.download_weather_data manual__2023-03-25T20:19:30.938712+00:00 [running]> on host 2414b9086979
[2023-03-25T20:19:32.252+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data_v0
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T20:19:30.938712+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-25T20:19:30.938712+00:00
[2023-03-25T20:19:32.892+0000] {get_weather_data.py:85} ERROR - An error occurred when trying to retrieve the weather data. Error:
Could not retrieve weather data. Response code: 404.
Response message: <!DOCTYPE html>
<html lang="es-es" dir="ltr">
<head>
	<meta charset="utf-8" />
	<title>404 - Artículo no encontrado</title>
	<link href="/templates/system/css/error.css" rel="stylesheet" />
			<!--[if lt IE 9]><script src="/media/jui/js/html5.js"></script><![endif]-->
</head>
<body>
	<div class="error">
		<div id="outline">
		<div id="errorboxoutline">
			<div id="errorboxheader">404 - Artículo no encontrado</div>
			<div id="errorboxbody">
			<p><strong>No puede visitar esta página debido a:</strong></p>
			<ol>
				<li>Un <strong>marcador o favorito caducado</strong></li>
				<li>Un motor de búsquedas que tiene un <strong>listado caducado para este sitio</strong></li>
				<li>Una <strong>dirección mal escrita</strong></li>
				<li>Usted no tiene <strong>acceso</strong> a esta página</li>
				<li>No se pudo encontrar el recurso solicitado.</li>
				<li>Se ha producido un error mientras se procesaba su solicitud.</li>
			</ol>
			<p><strong>Por favor, pruebe con alguna de las páginas siguientes:</strong></p>
			<ul>
				 
<!-- <li><a href="/index.php" title="Ir a la página de inicio">Página de inicio</a></li>
-->
			</ul>
			<p>Si la dificultad persiste, por favor, contacte con el administrador del sistema de este sitio y reporte el error de más abajo.</p>
			<div id="techinfo">
			<p>
				Artículo no encontrado							</p>
						</div>
			</div>
		</div>
		</div>
	</div>
</body>
</html>

[2023-03-25T20:19:32.892+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_weather_data.py", line 82, in download_weather_data
    raise ValueError(f"Could not retrieve weather data. Response code: {response.status_code}.\nResponse message: {response.text}")
ValueError: Could not retrieve weather data. Response code: 404.
Response message: <!DOCTYPE html>
<html lang="es-es" dir="ltr">
<head>
	<meta charset="utf-8" />
	<title>404 - Artículo no encontrado</title>
	<link href="/templates/system/css/error.css" rel="stylesheet" />
			<!--[if lt IE 9]><script src="/media/jui/js/html5.js"></script><![endif]-->
</head>
<body>
	<div class="error">
		<div id="outline">
		<div id="errorboxoutline">
			<div id="errorboxheader">404 - Artículo no encontrado</div>
			<div id="errorboxbody">
			<p><strong>No puede visitar esta página debido a:</strong></p>
			<ol>
				<li>Un <strong>marcador o favorito caducado</strong></li>
				<li>Un motor de búsquedas que tiene un <strong>listado caducado para este sitio</strong></li>
				<li>Una <strong>dirección mal escrita</strong></li>
				<li>Usted no tiene <strong>acceso</strong> a esta página</li>
				<li>No se pudo encontrar el recurso solicitado.</li>
				<li>Se ha producido un error mientras se procesaba su solicitud.</li>
			</ol>
			<p><strong>Por favor, pruebe con alguna de las páginas siguientes:</strong></p>
			<ul>
				 
<!-- <li><a href="/index.php" title="Ir a la página de inicio">Página de inicio</a></li>
-->
			</ul>
			<p>Si la dificultad persiste, por favor, contacte con el administrador del sistema de este sitio y reporte el error de más abajo.</p>
			<div id="techinfo">
			<p>
				Artículo no encontrado							</p>
						</div>
			</div>
		</div>
		</div>
	</div>
</body>
</html>

[2023-03-25T20:19:32.907+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=get_weather_data_v0, task_id=download_weather_data, execution_date=20230325T201930, start_date=20230325T201931, end_date=20230325T201932
[2023-03-25T20:19:32.932+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task download_weather_data (Could not retrieve weather data. Response code: 404.
Response message: <!DOCTYPE html>
<html lang="es-es" dir="ltr">
<head>
	<meta charset="utf-8" />
	<title>404 - Artículo no encontrado</title>
	<link href="/templates/system/css/error.css" rel="stylesheet" />
			<!--[if lt IE 9]><script src="/media/jui/js/html5.js"></script><![endif]-->
</head>
<body>
	<div class="error">
		<div id="outline">
		<div id="errorboxoutline">
			<div id="errorboxheader">404 - Artículo no encontrado</div>
			<div id="errorboxbody">
			<p><strong>No puede visitar esta página debido a:</strong></p>
			<ol>
				<li>Un <strong>marcador o favorito caducado</strong></li>
				<li>Un motor de búsquedas que tiene un <strong>listado caducado para este sitio</strong></li>
				<li>Una <strong>dirección mal escrita</strong></li>
				<li>Usted no tiene <strong>acceso</strong> a esta página</li>
				<li>No se pudo encontrar el recurso solicitado.</li>
				<li>Se ha producido un error mientras se procesaba su solicitud.</li>
			</ol>
			<p><strong>Por favor, pruebe con alguna de las páginas siguientes:</strong></p>
			<ul>
				 
<!-- <li><a href="/index.php" title="Ir a la página de inicio">Página de inicio</a></li>
-->
			</ul>
			<p>Si la dificultad persiste, por favor, contacte con el administrador del sistema de este sitio y reporte el error de más abajo.</p>
			<div id="techinfo">
			<p>
				Artículo no encontrado							</p>
						</div>
			</div>
		</div>
		</div>
	</div>
</body>
</html>
; 258)
[2023-03-25T20:19:32.981+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T20:19:33.024+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
