[2023-03-25T21:38:08.667+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data_v0.download_weather_data manual__2023-03-25T21:38:07.515732+00:00 [queued]>
[2023-03-25T21:38:08.680+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data_v0.download_weather_data manual__2023-03-25T21:38:07.515732+00:00 [queued]>
[2023-03-25T21:38:08.680+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T21:38:08.680+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T21:38:08.680+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T21:38:08.699+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 21:38:07.515732+00:00
[2023-03-25T21:38:08.705+0000] {standard_task_runner.py:55} INFO - Started process 267 to run task
[2023-03-25T21:38:08.709+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data_v0', 'download_weather_data', 'manual__2023-03-25T21:38:07.515732+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmpveyfi4pk']
[2023-03-25T21:38:08.712+0000] {standard_task_runner.py:83} INFO - Job 4: Subtask download_weather_data
[2023-03-25T21:38:08.788+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data_v0.download_weather_data manual__2023-03-25T21:38:07.515732+00:00 [running]> on host 8647624ffe94
[2023-03-25T21:38:08.893+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data_v0
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T21:38:07.515732+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-25T21:38:07.515732+00:00
[2023-03-25T21:38:09.612+0000] {get_weather_data.py:48} INFO - Decompressing .gz weather data...
[2023-03-25T21:38:09.647+0000] {get_weather_data.py:50} INFO - Decompression successful!
[2023-03-25T21:38:09.647+0000] {get_weather_data.py:57} INFO - Parsing json weather data...
[2023-03-25T21:38:09.819+0000] {get_weather_data.py:59} INFO - Parsing successful!
[2023-03-25T21:38:09.820+0000] {get_weather_data.py:72} INFO - Writing current data...
[2023-03-25T21:38:09.914+0000] {get_weather_data.py:74} INFO - Successfully created current_weather_data.parquet file!...
[2023-03-25T21:38:09.914+0000] {get_weather_data.py:76} INFO - Appending to historic data...
[2023-03-25T21:38:09.915+0000] {get_weather_data.py:88} ERROR - An error occurred when trying to retrieve the weather data. Error:
[Errno 2] No such file or directory: '/opt/***/dags/data//raw/historic_weather_data.parquet'
[2023-03-25T21:38:09.915+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_weather_data.py", line 78, in download_weather_data
    history = pd.read_parquet(path=f"{base_output_path}/raw/historic_weather_data.parquet")
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 500, in read_parquet
    **kwargs,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 236, in read
    mode="rb",
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parquet.py", line 102, in _get_path_or_handle
    path_or_handle, mode, is_text=False, storage_options=storage_options
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 711, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/data//raw/historic_weather_data.parquet'
[2023-03-25T21:38:09.924+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=get_weather_data_v0, task_id=download_weather_data, execution_date=20230325T213807, start_date=20230325T213808, end_date=20230325T213809
[2023-03-25T21:38:09.941+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 4 for task download_weather_data ([Errno 2] No such file or directory: '/opt/airflow/dags/data//raw/historic_weather_data.parquet'; 267)
[2023-03-25T21:38:09.963+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T21:38:09.998+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
