[2023-03-25T14:13:44.337+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data manual__2023-03-25T14:13:44.005603+00:00 [queued]>
[2023-03-25T14:13:44.346+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data manual__2023-03-25T14:13:44.005603+00:00 [queued]>
[2023-03-25T14:13:44.347+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:13:44.347+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T14:13:44.347+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:13:44.360+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 14:13:44.005603+00:00
[2023-03-25T14:13:44.364+0000] {standard_task_runner.py:55} INFO - Started process 246 to run task
[2023-03-25T14:13:44.367+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data', 'download_weather_data', 'manual__2023-03-25T14:13:44.005603+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmpx2ggna01']
[2023-03-25T14:13:44.368+0000] {standard_task_runner.py:83} INFO - Job 5: Subtask download_weather_data
[2023-03-25T14:13:44.420+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data.download_weather_data manual__2023-03-25T14:13:44.005603+00:00 [running]> on host f9474b81b935
[2023-03-25T14:13:44.492+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T14:13:44.005603+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-25T14:13:44.005603+00:00
[2023-03-25T14:13:45.340+0000] {get_weather_data.py:70} ERROR - An error occurred when trying to retrieve the weather data. Error:
name 'BASE_URL' is not defined
[2023-03-25T14:13:45.340+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-25T14:13:45.349+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=get_weather_data, task_id=download_weather_data, execution_date=20230325T141344, start_date=20230325T141344, end_date=20230325T141345
[2023-03-25T14:13:45.381+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-25T14:13:45.397+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
