[2023-03-25T22:28:25.532+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data_v0.download_weather_data scheduled__2023-03-25T21:00:00+00:00 [queued]>
[2023-03-25T22:28:25.540+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data_v0.download_weather_data scheduled__2023-03-25T21:00:00+00:00 [queued]>
[2023-03-25T22:28:25.540+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T22:28:25.540+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T22:28:25.540+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T22:28:25.553+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 21:00:00+00:00
[2023-03-25T22:28:25.557+0000] {standard_task_runner.py:55} INFO - Started process 220 to run task
[2023-03-25T22:28:25.560+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data_v0', 'download_weather_data', 'scheduled__2023-03-25T21:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmpdd2w47z5']
[2023-03-25T22:28:25.561+0000] {standard_task_runner.py:83} INFO - Job 7: Subtask download_weather_data
[2023-03-25T22:28:25.615+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data_v0.download_weather_data scheduled__2023-03-25T21:00:00+00:00 [running]> on host eb99e9ad14f4
[2023-03-25T22:28:25.828+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data_v0
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T21:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T21:00:00+00:00
[2023-03-25T22:28:25.996+0000] {get_weather_data.py:88} ERROR - An error occurred when trying to retrieve the weather data. Error:
Could not retrieve weather data. Response code: 404.
Response message: <!DOCTYPE html>
<html lang="es-es" dir="ltr">
<head>
	<meta charset="utf-8" />
	<title>404 - Artículo no encontrado</title>
	<link href="/templates/system/css/error.css" rel="stylesheet" />
			<!--[if lt IE 9]><script src="/media/jui/js/html5.js"></script><![endif]-->
</head>
<body>
	<div class="error">
		<div id="outline">
		<div id="errorboxoutline">
			<div id="errorboxheader">404 - Artículo no encontrado</div>
			<div id="errorboxbody">
			<p><strong>No puede visitar esta página debido a:</strong></p>
			<ol>
				<li>Un <strong>marcador o favorito caducado</strong></li>
				<li>Un motor de búsquedas que tiene un <strong>listado caducado para este sitio</strong></li>
				<li>Una <strong>dirección mal escrita</strong></li>
				<li>Usted no tiene <strong>acceso</strong> a esta página</li>
				<li>No se pudo encontrar el recurso solicitado.</li>
				<li>Se ha producido un error mientras se procesaba su solicitud.</li>
			</ol>
			<p><strong>Por favor, pruebe con alguna de las páginas siguientes:</strong></p>
			<ul>
				<li><a href="/index.php" title="Ir a la página de inicio">Página de inicio</a></li>
			</ul>
			<p>Si la dificultad persiste, por favor, contacte con el administrador del sistema de este sitio y reporte el error de más abajo.</p>
			<div id="techinfo">
			<p>
				Artículo no encontrado							</p>
						</div>
			</div>
		</div>
		</div>
	</div>
</body>
</html>

[2023-03-25T22:28:25.996+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_weather_data.py", line 85, in download_weather_data
    raise ValueError(f"Could not retrieve weather data. Response code: {response.status_code}.\nResponse message: {response.text}")
ValueError: Could not retrieve weather data. Response code: 404.
Response message: <!DOCTYPE html>
<html lang="es-es" dir="ltr">
<head>
	<meta charset="utf-8" />
	<title>404 - Artículo no encontrado</title>
	<link href="/templates/system/css/error.css" rel="stylesheet" />
			<!--[if lt IE 9]><script src="/media/jui/js/html5.js"></script><![endif]-->
</head>
<body>
	<div class="error">
		<div id="outline">
		<div id="errorboxoutline">
			<div id="errorboxheader">404 - Artículo no encontrado</div>
			<div id="errorboxbody">
			<p><strong>No puede visitar esta página debido a:</strong></p>
			<ol>
				<li>Un <strong>marcador o favorito caducado</strong></li>
				<li>Un motor de búsquedas que tiene un <strong>listado caducado para este sitio</strong></li>
				<li>Una <strong>dirección mal escrita</strong></li>
				<li>Usted no tiene <strong>acceso</strong> a esta página</li>
				<li>No se pudo encontrar el recurso solicitado.</li>
				<li>Se ha producido un error mientras se procesaba su solicitud.</li>
			</ol>
			<p><strong>Por favor, pruebe con alguna de las páginas siguientes:</strong></p>
			<ul>
				<li><a href="/index.php" title="Ir a la página de inicio">Página de inicio</a></li>
			</ul>
			<p>Si la dificultad persiste, por favor, contacte con el administrador del sistema de este sitio y reporte el error de más abajo.</p>
			<div id="techinfo">
			<p>
				Artículo no encontrado							</p>
						</div>
			</div>
		</div>
		</div>
	</div>
</body>
</html>

[2023-03-25T22:28:26.008+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=get_weather_data_v0, task_id=download_weather_data, execution_date=20230325T210000, start_date=20230325T222825, end_date=20230325T222826
[2023-03-25T22:28:26.024+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7 for task download_weather_data (Could not retrieve weather data. Response code: 404.
Response message: <!DOCTYPE html>
<html lang="es-es" dir="ltr">
<head>
	<meta charset="utf-8" />
	<title>404 - Artículo no encontrado</title>
	<link href="/templates/system/css/error.css" rel="stylesheet" />
			<!--[if lt IE 9]><script src="/media/jui/js/html5.js"></script><![endif]-->
</head>
<body>
	<div class="error">
		<div id="outline">
		<div id="errorboxoutline">
			<div id="errorboxheader">404 - Artículo no encontrado</div>
			<div id="errorboxbody">
			<p><strong>No puede visitar esta página debido a:</strong></p>
			<ol>
				<li>Un <strong>marcador o favorito caducado</strong></li>
				<li>Un motor de búsquedas que tiene un <strong>listado caducado para este sitio</strong></li>
				<li>Una <strong>dirección mal escrita</strong></li>
				<li>Usted no tiene <strong>acceso</strong> a esta página</li>
				<li>No se pudo encontrar el recurso solicitado.</li>
				<li>Se ha producido un error mientras se procesaba su solicitud.</li>
			</ol>
			<p><strong>Por favor, pruebe con alguna de las páginas siguientes:</strong></p>
			<ul>
				<li><a href="/index.php" title="Ir a la página de inicio">Página de inicio</a></li>
			</ul>
			<p>Si la dificultad persiste, por favor, contacte con el administrador del sistema de este sitio y reporte el error de más abajo.</p>
			<div id="techinfo">
			<p>
				Artículo no encontrado							</p>
						</div>
			</div>
		</div>
		</div>
	</div>
</body>
</html>
; 220)
[2023-03-25T22:28:26.052+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T22:28:26.096+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-25T22:30:55.755+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data_v0.download_weather_data scheduled__2023-03-25T21:00:00+00:00 [queued]>
[2023-03-25T22:30:55.774+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data_v0.download_weather_data scheduled__2023-03-25T21:00:00+00:00 [queued]>
[2023-03-25T22:30:55.774+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T22:30:55.774+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T22:30:55.774+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T22:30:55.787+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 21:00:00+00:00
[2023-03-25T22:30:55.791+0000] {standard_task_runner.py:55} INFO - Started process 214 to run task
[2023-03-25T22:30:55.793+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data_v0', 'download_weather_data', 'scheduled__2023-03-25T21:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmpor8k9i0e']
[2023-03-25T22:30:55.794+0000] {standard_task_runner.py:83} INFO - Job 3: Subtask download_weather_data
[2023-03-25T22:30:55.871+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data_v0.download_weather_data scheduled__2023-03-25T21:00:00+00:00 [running]> on host 1e7d3c0923c5
[2023-03-25T22:30:55.967+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data_v0
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T21:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T21:00:00+00:00
[2023-03-25T22:30:56.050+0000] {get_weather_data.py:48} INFO - Decompressing .gz weather data...
[2023-03-25T22:30:56.081+0000] {get_weather_data.py:50} INFO - Decompression successful!
[2023-03-25T22:30:56.082+0000] {get_weather_data.py:57} INFO - Parsing json weather data...
[2023-03-25T22:30:56.216+0000] {get_weather_data.py:59} INFO - Parsing successful!
[2023-03-25T22:30:56.218+0000] {get_weather_data.py:72} INFO - Writing current data...
[2023-03-25T22:30:56.317+0000] {get_weather_data.py:74} INFO - Successfully created current_weather_data.parquet file!...
[2023-03-25T22:30:56.317+0000] {get_weather_data.py:76} INFO - Appending to historic data...
[2023-03-25T22:30:56.333+0000] {get_weather_data.py:83} INFO - Successfully appended new data to historic_weather_data.parquet file!
[2023-03-25T22:30:56.336+0000] {python.py:177} INFO - Done. Returned value was: None
[2023-03-25T22:30:56.346+0000] {taskinstance.py:1326} INFO - Marking task as SUCCESS. dag_id=get_weather_data_v0, task_id=download_weather_data, execution_date=20230325T210000, start_date=20230325T223055, end_date=20230325T223056
[2023-03-25T22:30:56.367+0000] {local_task_job.py:212} INFO - Task exited with return code 0
[2023-03-25T22:30:56.420+0000] {taskinstance.py:2585} INFO - 1 downstream tasks scheduled from follow-on schedule check
