[2023-03-25T14:48:46.434+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T07:00:00+00:00 [queued]>
[2023-03-25T14:48:46.455+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T07:00:00+00:00 [queued]>
[2023-03-25T14:48:46.456+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:48:46.456+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T14:48:46.456+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T14:48:46.484+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 07:00:00+00:00
[2023-03-25T14:48:46.493+0000] {standard_task_runner.py:55} INFO - Started process 272 to run task
[2023-03-25T14:48:46.499+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data', 'download_weather_data', 'scheduled__2023-03-25T07:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmphc6pp7t8']
[2023-03-25T14:48:46.502+0000] {standard_task_runner.py:83} INFO - Job 11: Subtask download_weather_data
[2023-03-25T14:48:46.599+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T07:00:00+00:00 [running]> on host dbbe6b1163d2
[2023-03-25T14:48:46.715+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T07:00:00+00:00
[2023-03-25T14:48:47.533+0000] {get_weather_data.py:84} ERROR - An error occurred when trying to retrieve the weather data. Error:
Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}
[2023-03-25T14:48:47.534+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_weather_data.py", line 81, in download_weather_data
    raise ValueError("Could not retrieve weather data. Response code: {response.status_code}.\nResponse message: {response.text}")
ValueError: Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}
[2023-03-25T14:48:47.544+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=get_weather_data, task_id=download_weather_data, execution_date=20230325T070000, start_date=20230325T144846, end_date=20230325T144847
[2023-03-25T14:48:47.591+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 11 for task download_weather_data (Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}; 272)
[2023-03-25T14:48:47.634+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T14:48:47.663+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-25T19:30:21.755+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T07:00:00+00:00 [queued]>
[2023-03-25T19:30:21.774+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T07:00:00+00:00 [queued]>
[2023-03-25T19:30:21.775+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T19:30:21.775+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 6
[2023-03-25T19:30:21.775+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-25T19:30:21.880+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): download_weather_data> on 2023-03-25 07:00:00+00:00
[2023-03-25T19:30:21.888+0000] {standard_task_runner.py:55} INFO - Started process 226 to run task
[2023-03-25T19:30:21.893+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_weather_data', 'download_weather_data', 'scheduled__2023-03-25T07:00:00+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/get_weather_data.py', '--cfg-path', '/tmp/tmpd_xec8mq']
[2023-03-25T19:30:21.896+0000] {standard_task_runner.py:83} INFO - Job 10: Subtask download_weather_data
[2023-03-25T19:30:22.016+0000] {task_command.py:388} INFO - Running <TaskInstance: get_weather_data.download_weather_data scheduled__2023-03-25T07:00:00+00:00 [running]> on host 81679e29af39
[2023-03-25T19:30:22.208+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=AlexDeLara
AIRFLOW_CTX_DAG_ID=get_weather_data
AIRFLOW_CTX_TASK_ID=download_weather_data
AIRFLOW_CTX_EXECUTION_DATE=2023-03-25T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-25T07:00:00+00:00
[2023-03-25T19:30:23.527+0000] {get_weather_data.py:84} ERROR - An error occurred when trying to retrieve the weather data. Error:
Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}
[2023-03-25T19:30:23.529+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/get_weather_data.py", line 81, in download_weather_data
    raise ValueError("Could not retrieve weather data. Response code: {response.status_code}.\nResponse message: {response.text}")
ValueError: Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}
[2023-03-25T19:30:23.542+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=get_weather_data, task_id=download_weather_data, execution_date=20230325T070000, start_date=20230325T193021, end_date=20230325T193023
[2023-03-25T19:30:23.576+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 10 for task download_weather_data (Could not retrieve weather data. Response code: {response.status_code}.
Response message: {response.text}; 226)
[2023-03-25T19:30:23.635+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-25T19:30:23.950+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
